services:
    nginx:
        image: nginx:1.25.1
        container_name: ${APP_NAME}_nginx
        ports:
        - '${APP_PORT:-80}:80'
        volumes:
        - ./:/usr/share/nginx/html
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
        - app

    app:
        container_name: ${APP_NAME}_app
        build:
            context: ./docker/php
        volumes:
        - ./:/usr/share/nginx/html
        depends_on:
        - db

    db:
        container_name: ${APP_NAME}_db
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_USER: ${DB_USERNAME}'
        ports:
        - '${DB_PORT:-3306}:3306'