version: '3'

services:
  nginx:
    image: nginx:1.25.1
    ports:
      - 80:80
    volumes:
      - ./public:/usr/share/nginx/html
      - ./public/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    volumes:
      - ./public:/usr/share/nginx/html